apiVersion: v1 # v1 consists of resources such Pod Service Secret whereas apps/v1 has Deployment
# rule of thumb just look at an example manifest file for resource to determine api version
kind: Pod # is the kind of resource you want to create pod, deployment or service
metadata: # 
  name: client-pod
  labels: 
    app: client
spec:
  containers:
    - name: client
      image: laithharb/web-app:v1