apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata: # label or name you can give to your resource
      name: client-pod # name of the resource it can be anything you like.
      # this is the name displayed when you run the kubectl get pod command
      labels: 
        app: client
      # labels are given to resources so that other resources can interact with them
      # you can multiple lables attached to each resource 
      # the keys can vary alot. the labels can be monkeys or bananas
      # 
    spec:
      containers:
        - name: client
          image: laithharb/web-app:v1

---

apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 3000 # key is used to define the internal communication from pod to pod
      targetPort: 3000 # this is the port that is exposed inside the container
      nodePort: 30007 # this is a special port that is only assigned when you have a type of service allled nodeport. 
                      # this is the port that the browser and the kube-proxy replies on 
                      # to the browser