apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec: # Spec of deployment
  replicas: 3
  selector: 
    matchLabels:
      app: server
  template:
    metadata:
      name: server-pod
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: laithharb/server:v1
